### PR TITLE
Fix export to JPEG

### PR DESCRIPTION
**Pull request by diodfr**
The JPEG format exports files with alpha because only JPG extension is managed.

### CODE REVIEW

**Comment by wmnwmn** [comment]
I really want to pick up this fix however cannot seem to build the project. Maven is new to me, that's probably the problem, but I am getting test failures that stop the build. Can someone point me to a clue how to compile the project?

**Comment by diodfr** [comment]
Could you give me more details ? What the error looks like ?

**Comment by mikucionisaau** [comment]
I also get test failures (probably some path variable is messed up), I just skip tests like this:

mvn -Dmaven.test.skip=true
mvn -Dmaven.test.skip=true source:jar 
mvn -Dmaven.test.skip=true javadoc:jar

**Comment by wmnwmn** [comment]
Thanks guys, the test skipping does work. Also here's the error I was
getting, at least the start, which does seem like a path:

---

##  T E S T S

Running org.freehep.graphicsbase.util.test.ScientificFormatTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.076 sec
Running org.freehep.graphicsbase.xml.util.test.TestXMLWriter
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.019 sec
<<< FAILURE!
testXML(org.freehep.graphicsbase.xml.util.test.TestXMLWriter)  Time
elapsed: 17 sec  <<< ERROR!
java.io.FileNotFoundException:
../freehep-graphicsbase/src/test/resources/org/freehep/graphicsbase/util/export/test/TestXMLWriter.xml
(No such file or directory)
at java.io.FileInputStream.open(Native Method)
at java.io.FileInputStream.<init>(FileInputStream.java:120)
at org.freehep.graphicsbase.util.Assert.assertEquals(Assert.java:43)
at
org.freehep.graphicsbase.xml.util.test.TestXMLWriter.testXML(TestXMLWriter.java:60)

On Fri, Feb 7, 2014 at 7:22 AM, Marius Mikučionis
notifications@github.comwrote:

> I also get test failures (probably some path variable is messed up), I
> just skip tests like this:
> 
> mvn -Dmaven.test.skip=true
> mvn -Dmaven.test.skip=true source:jar
> mvn -Dmaven.test.skip=true javadoc:jar
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/freehep/freehep-vectorgraphics/pull/16#issuecomment-34440034
> .

## 

Will Nelson
AGCOL/Bio5
University of Arizona

**Pull request merged**
